treatments:
  - name: solo
    factorIds:
      - yLgJTwkJB3dh4jh3r
      - A6nriq6uaerSLGxv2
      - j7dzgP5Bf5XqdBiNG
      - iZyssrDWEYhnc8Q7B
      - RhXZkZdj5fYbQNssb
      - nNqv434CrsBRjkPLE
      - vcCNgQk3ChHgGSLLF
  - name: team
    factorIds:
      - DjKCDtyNpyHu7XvP9
      - A6nriq6uaerSLGxv2
      - j7dzgP5Bf5XqdBiNG
      - iZyssrDWEYhnc8Q7B
      - RhXZkZdj5fYbQNssb
      - nNqv434CrsBRjkPLE
      - vcCNgQk3ChHgGSLLF
      - HjKCDtyNyyHu7XvW9
  - name: team_long
    factorIds:
      - DjKCDtyNpyHu7XvP9
      - TNyTTdPz4iNutcq68
      - j7dzgP5Bf5XqdBiNG
      - t8JscYzadj76bngCD
      - tXtK9D88FvXWay7kQ
      - nNqv434CrsBRjkPLE
      - vv9nHoqDp2DDjXkkK
      - HjKCDtyNyyHu7XvW9
factorTypes:
  - _id: zjbEtHuHFWSvhDdZS
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
  - _id: ZzHiS2M4TFGPQRPsL
    name: stageDuration
    description: Specifies how many seconds for each decision stage
    required: false
    type: Integer
    min: 5
    max: 10000
  - _id: YuxymxgdicnLpwqQq
    name: stepOne
    description: SequenceOne of 5 tasks or SequenceTwo of 5 tasks
    required: true
    type: Boolean
  - _id: rfisFt6sGMhs7FN4P
    name: taskOrder
    description: How to do the sequence to be ordered
    required: false
    type: String
    archivedAt: 2018-10-15T17:22:05.622Z
  - _id: K5zoaut98tuZsmpa7
    name: basePay
    description: 'The amount for base pay (i.e., showing up and completing the experiment)'
    required: false
    type: Number
    min: 0
    max: 1
  - _id: CgCzQdbcMNh6JqAZT
    name: conversionRate
    description: This will be multiplied by their total score to compute the bonus
    required: false
    type: Number
    min: 0
    max: 10
  - _id: 9HMtrxYDhvFhhcrzM
    name: optimalSolutionBonus
    description: 'For each optimal solution, what is the additional bonus? (in dollars)'
    required: false
    type: Number
    min: 0
    max: 10
  - _id: gyMzogFBfCYjqZmz3
    name: shuffleTaskOrder
    description: How to do the sequence to be ordered
    required: false
    type: Boolean
  - _id: a7jTKqh7eJr4zvSQ9
    name: botsCount
    description: The Number of bots participating in the given game.
    required: true
    type: Integer
    min: 1
factors:
  - _id: GjzrZDckwymcfCcqi
    name: 'true'
    value: true
    factorTypeId: YuxymxgdicnLpwqQq
  - _id: j7dzgP5Bf5XqdBiNG
    name: 'false'
    value: false
    factorTypeId: YuxymxgdicnLpwqQq
  - _id: vcCNgQk3ChHgGSLLF
    name: 'true'
    value: true
    factorTypeId: gyMzogFBfCYjqZmz3
  - _id: vv9nHoqDp2DDjXkkK
    name: 'false'
    value: false
    factorTypeId: gyMzogFBfCYjqZmz3
  - _id: yLgJTwkJB3dh4jh3r
    name: solo
    value: 1
    factorTypeId: zjbEtHuHFWSvhDdZS
  - _id: DjKCDtyNpyHu7XvP9
    name: team
    value: 2
    factorTypeId: zjbEtHuHFWSvhDdZS
  - _id: A6nriq6uaerSLGxv2
    name: 5min
    value: 300
    factorTypeId: ZzHiS2M4TFGPQRPsL
  - _id: t8JscYzadj76bngCD
    name: none
    value: 0
    factorTypeId: K5zoaut98tuZsmpa7
  - _id: iZyssrDWEYhnc8Q7B
    name: oneDollar
    value: 1
    factorTypeId: K5zoaut98tuZsmpa7
  - _id: tXtK9D88FvXWay7kQ
    name: none
    value: 0
    factorTypeId: CgCzQdbcMNh6JqAZT
  - _id: RhXZkZdj5fYbQNssb
    name: small
    value: 0.00001
    factorTypeId: CgCzQdbcMNh6JqAZT
  - _id: nNqv434CrsBRjkPLE
    name: 50cents
    value: 0.5
    factorTypeId: 9HMtrxYDhvFhhcrzM
  - _id: HjKCDtyNyyHu7XvW9
    name: bob
    value: 1
    factorTypeId: a7jTKqh7eJr4zvSQ9
  - _id: TNyTTdPz4iNutcq68
    name: 30min
    value: 1800
    factorTypeId: ZzHiS2M4TFGPQRPsL
lobbyConfigs:
  - timeoutType: lobby
    timeoutInSeconds: 300
    timeoutStrategy: fail
    gameLobbyIds: []
  - name: prod
    timeoutType: individual
    timeoutInSeconds: 300
    timeoutStrategy: fail
    extendCount: 0
    gameLobbyIds: []
    archivedAt: 2021-09-26T09:56:09.748Z
  - name: emp_prod
    timeoutType: individual
    timeoutInSeconds: 300
    timeoutStrategy: fail
    extendCount: 0
    gameLobbyIds: []
